line-length = 99

[lint]
preview = true
select = ["ERA", "E", "F", "UP", "B", "SIM", "I"]
ignore = ["UP007", "UP045"]

[lint.pydocstyle]
convention = "google"

[format]
preview = true
docstring-code-format = true
