line-length = 99

[lint]
preview = true
select = ["E", "F", "UP", "B", "SIM", "I"]
ignore = ["UP007", "UP045", "E701"]

[lint.pydocstyle]
convention = "google"

[format]
preview = true
docstring-code-format = true
